[package]
name = "tesuto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.4"
serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"
