[package]
name = "tesuto"
description = "Lightweight testing tool."
authors = ["Konstantin Zhigaylo <zero@kostyazero.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://git.kostyazero.com/kostya-zero/tesuto"
version = "0.2.0-dev"
edition = "2021"

[dependencies]
clap = "4.4.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
