name: Tesuto
scenarios:
  test:
  - hello
stages:
  build:
    before_script: []
    script:
    - cargo build
    variables: {}
    quite: false
  clippy:
    before_script: []
    script:
    - cargo clippy
    variables: {}
    quite: false
