name: Tesuto
stages:
  clippy:
    before_script: []
    script: 
    - cargo clippy
    variables: {}
    quite: false
  build:
    before_script: []
    script: 
    - cargo build
    variables: {}
    quite: false
