[package]
name = "tesuto"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = "4.4.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
tesuto_project = { path = "../tesuto_project" }
