name: Build Binary

on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            bin: tesuto
          - os: macos-latest
            target: aarch64-apple-darwin
            bin: tesuto
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: tesuto
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: tesuto.exe
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Build Release Binary
        run: cargo build --release
      - name: Upload as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tesuto-${{ matrix.target }}
          path: target/release/${{ matrix.bin }}
